#!/bin/sh
cd $(dirname $0)/..
tar -cz \
    --exclude-vcs \
    --exclude-vcs-ignores \
    --exclude=.github \
    --exclude=tree-sitter/test \
    --exclude=tree-sitter-java \
    -f tree-sitter.tar.gz \
    tree-sitter